### PR TITLE
Added Esc function for clearing input field

### PR DESCRIPTION
**Pull request by ToastyStoemp**
Users can now clear the text field by pressing Esc

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Ctrl-A, Backspace works natively.

**Comment by WebFreak001** [comment]
+1 to merge this

**Comment by M4GNV5** [comment]
+1

**Comment by M4GNV5** [comment]
+1 (or +2 actually)

**Comment by AndrewBelt** [comment]
Okay, sure. Thanks.

**Pull request merged**
