### PR TITLE
Fixed question mark in latex issue. closes #39

### LINKED ISSUE #39: Questions Marks in LaTeX
`$ {?} $` This creates a link instead of using Latex.

### PR DESCRIPTION
**Pull request by BitByBen**

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Breaks on channels starting on the second newline `?meta\n?lobby`, and inside parenthesis `(?lobby)`, as can be seen on the homepage. It's close though. I'd like to try to create a simple context-free parser with regex tokens in Javascript, and then we could handle 100% of these dumb cases, and get rid of auto-render.js from KaTeX.

**Comment by BitByBen** [comment]
Okay. I'll just make the parser better. 1 sec.

**Comment by BitByBen** [comment]
Okie dokie. Try that out @AndrewBelt

**Comment by BitByBen** [comment]
Hm. Still broke. Nevermind. Will try again.

**Comment by BitByBen** [comment]
Okay.... I've got everything expect the one link of the front page working. My brain has decided to stop logically working for the moment.

**Pull request closed without merging**
