### PR TITLE
added saving of multiple 'lastSent' messages

### PR DESCRIPTION
**Pull request by M4GNV5**
arrow up & arrow down for scrolling through all previous sent messages

### CODE REVIEW

**Comment by AndrewBelt** [comment]
What if I want to use the arrow keys to move up and down through the multiple lines of the input box? That's why it only supports the last message by design.

**Comment by M4GNV5** [comment]
what if i want to use the arrow keys to scroll through the chat history? :stuck_out_tongue: 
anyways maybe i can figure something out for changing between going through lines and viewing previous messages

**Comment by AndrewBelt** [comment]
Perhaps Ctrl-Up/Down or Shift-Up/Down? But it would be difficult to figure that out by chance without reading some sort of documentation.

**Comment by M4GNV5** [comment]
okay i added suppor for multi line messages and multiple messages in lastSent now
its hard to explain how it works so i made a video: https://dl.dropboxusercontent.com/u/72274197/prShowcase.ogv

**Comment by M4GNV5** [comment]
okay so i resolved the conflicts and added that the lastSent messages get cleared when clearing chat history

**Comment by WebFreak001** [comment]
I dont think this is hard to figure it out because its also in skype and they figured out there too

**Comment by M4GNV5** [comment]
again i fixed conflicts so this is a one-click merge...

**Pull request merged**
